<?xml version="1.0" encoding="utf-8"?><Database Name="aspnet-Better-20171013095525" Class="BetterDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\aspnet-Better-20171013095525.mdf;Initial Catalog=aspnet-Better-20171013095525;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AspNetTitans" Member="AspNetTitans">
    <Type Name="AspNetTitan">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TitanName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Exp" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Wins" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Losses" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Draws" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Retired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="AspNetTitan_AspNetUserTitan" Member="AspNetUserTitans" ThisKey="Id" OtherKey="TitanID" Type="AspNetUserTitan" />
      <Association Name="AspNetTitan_AspNetUserTitanFight" Member="AspNetUserTitanFights" ThisKey="Id" OtherKey="AttackerTitanID" Type="AspNetUserTitanFight" />
      <Association Name="AspNetTitan_AspNetUserTitanFight1" Member="AspNetUserTitanFights1" ThisKey="Id" OtherKey="DefenderTitanID" Type="AspNetUserTitanFight" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserTitans" Member="AspNetUserTitans">
    <Type Name="AspNetUserTitan">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="TitanID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Retired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="AspNetTitan_AspNetUserTitan" Member="AspNetTitan" ThisKey="TitanID" OtherKey="Id" Type="AspNetTitan" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserTitanFights" Member="AspNetUserTitanFights">
    <Type Name="AspNetUserTitanFight">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AttackerTitanID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DefenderTitanID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Win" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Loss" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Draw" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="AspNetTitan_AspNetUserTitanFight" Member="AspNetTitan" ThisKey="AttackerTitanID" OtherKey="Id" Type="AspNetTitan" IsForeignKey="true" />
      <Association Name="AspNetTitan_AspNetUserTitanFight1" Member="AspNetTitan1" ThisKey="DefenderTitanID" OtherKey="Id" Type="AspNetTitan" IsForeignKey="true" />
    </Type>
  </Table>
</Database>